---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    If Anissa doesn't earn an A, then nobody should because she consistently puts in effort to master the material, stay organized, and help classmates succeed.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    The most difficult part of this class was learning to logically build data pipelines— I am new to data transformations so having to think carefully about how each function connected to produce a desired output was difficult.

3.  What was the easiest part of the class for you? Explain why.

    The easiest part of this class was navigating the course website because it is so well organized and made all materials/ instructions easy to find and follow.

4.  What part of the class surprised or interested you the most? Explain why.

    The most interesting part of this class was discovering how different visualization techniques can reveal different patterns and tailored communicate insights across data sets.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    My advice to a future student is to explore package documentation, as understanding available function arguments will make your code cleaner and more efficient.
